jobs:
  release:
    name: Publish Plugin
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name }}
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      id: properties
      name: Export Properties
      run: 'CHANGELOG="$(cat << ''EOM'' | sed -e ''s/^[[:space:]]*$//g'' -e ''/./,$!d''

        ${{ github.event.release.body }}

        EOM

        )"


        echo "changelog<<EOF" >> $GITHUB_OUTPUT

        echo "$CHANGELOG" >> $GITHUB_OUTPUT

        echo "EOF" >> $GITHUB_OUTPUT

        '
      shell: bash
    - continue-on-error: true
      env:
        CHANGELOG: ${{ steps.properties.outputs.changelog }}
      if: ${{ steps.properties.outputs.changelog != '' }}
      name: Patch Changelog
      run: './gradlew patchChangelog --release-note="$CHANGELOG"

        '
    - continue-on-error: true
      env:
        CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      name: Publish Plugin
      run: ./gradlew publishPlugin
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Upload Release Asset
      run: gh release upload ${{ github.event.release.tag_name }} ./build/distributions/*
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ steps.properties.outputs.changelog != '' }}
      name: Create Pull Request
      run: "VERSION=\"${{ github.event.release.tag_name }}\"\nBRANCH=\"changelog-update-$VERSION\"\
        \nLABEL=\"release changelog\"\n\ngit config user.email \"action@github.com\"\
        \ngit config user.name \"GitHub Action\"\n\ngit checkout -b $BRANCH\ngit commit\
        \ -am \"Changelog update - $VERSION\"\ngit push --set-upstream origin $BRANCH\n\
        \ngh label create \"$LABEL\" \\\n  --description \"Pull requests with release\
        \ changelog update\" \\\n  || true\n\ngh pr create \\\n  --title \"Changelog\
        \ update - \\`$VERSION\\`\" \\\n  --body \"Current pull request contains patched\
        \ \\`CHANGELOG.md\\` file for the \\`$VERSION\\` version.\" \\\n  --label\
        \ \"$LABEL\" \\\n  --head $BRANCH"
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
